### ISSUE TITLE
输入baidu-life-translate后（输入任何单词如ant），出现以下错误信息，功能不能用。

### ISSUE THREAD

**Issue by marshalyyx2000** [lujun9972/el-baidu-life#1]
Contacting host: apis.baidu.com:80
setq: Invalid coding system: utf-8\">\

**Comment by lujun9972** [comment]
没想到还真有人用啊～～

**Comment by lujun9972** [comment]
你是在linux上用还是windows上用呢？

**Comment by marshalyyx2000** [comment]
我是在linux下用。

**Comment by marshalyyx2000** [comment]
希望能修正该bug。里面的中文翻译成英文在emacs下对于写代码命名挺好的。

**Comment by lujun9972** [comment]
抱歉，我调试了一下，发现这些API几乎都失效了，这个包没用了。
如果想要中文翻译的话，可以试试[youdao-dictionary](https://github.com/xuchunyang/youdao-dictionary.el)或者
[mdx-dictionary](https://github.com/lujun9972/mdx-dictionary.el)
